#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
---
static_resources:
  listeners:
    - name: "net/http"
      protocol_type: "HTTPS"
      address:
        socket_address:
          address: "0.0.0.0"
          port: 443
      filter_chains:
          filters:
            - name: dgp.filter.httpconnectionmanager
              config:
                idle_timeout: "100"
                route_config:
                  dynamic: false
                  routes:
                    - id: "1"
                      match:
                        prefix: "/api/v1"
                        path: ""
                        methods:
                          - POST
                      route:
                        cluster: "test_dubbo"
                        cluster_not_found_response_code: 505
                http_filters:
                  - name: dgp.filters.http.api
                    config:
                  - name: dgp.filters.http.router
                    config:
                  - name: dgp.filters.http.dubboproxy
                    config:
                server_name: "test_http_dubbo"
                generate_request_id: false
                timeout: "10s"
      config:
        idle_timeout: 5s
        read_timeout: 5s
        write_timeout: 5s
  clusters:
    - name: "test_dubbo"
      lb_policy: "RoundRobin"
  timeout_config:
    connect_timeout: "5s"
    request_timeout: "10s"
  shutdown_config:
    timeout: "60s"
    step_timeout: "10s"
    reject_policy: "immediacy"
  pprofConf:
    enable: true
    address:
      socket_address:
        address: "0.0.0.0"
        port: 6060