---
apiVersion: pixiu.apache.org/v1alpha1
kind: PixiuFilterPolicy
metadata:
  name: jwt-filter-policy
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend
  filterType: dgp.filter.http.auth.jwt
  config:
    rules:
      - match:
          prefix: /health
      - match:
          prefix: /user
        requires:
          requires_any:
            provider_name: provider1
      - match:
          prefix: /user/pixiu
        requires:
          requires_any:
            provider_name: provider2
      - match:
          prefix: /prefix
        requires:
          requires_all:
            - provider_name: provider1
            - provider_name: provider2
    providers:
      - name: provider1
        from_headers:
          name: Authorization
          value_prefix: "Bearer "
        forward_payload_header: user-data
        issuer: issuer1
        local_jwks:
          inline_string: "{\"keys\":[{\"kty\":\"RSA\",\"e\":\"AQAB\",\"kid\":\"ee8d626d\",\"n\":\"gRda5b0pkgTytDuLrRnNSYhvfMIyM0ASq2ZggY4dVe12JV8N7lyXilyqLKleD-2lziivvzE8O8CdIC2vUf0tBD7VuMyldnZruSEZWCuKJPdgKgy9yPpShmD2NyhbwQIAbievGMJIp_JMwz8MkdY5pzhPECGNgCEtUAmsrrctP5V8HuxaxGt9bb-DdPXkYWXW3MPMSlVpGZ5GiIeTABxqYNG2MSoYeQ9x8O3y488jbassTqxExI_4w9MBQBJR9HIXjWrrrenCcDlMY71rzkbdj3mmcn9xMq2vB5OhfHyHTihbUPLSm83aFWSuW9lE7ogMc93XnrB8evIAk6VfsYlS9Q\"}]}"
      - name: provider2
        from_headers:
          name: Authorization
          value_prefix: "Bearer "
        forward_payload_header: user-data
        issuer: issuer2
        remote_jwks:
          http_uri:
            uri: http://127.0.0.1:1314/remote
            timeout: 5s
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend
  namespace: default
spec:
  parentRefs:
    - name: pg
      namespace: pixiu-gateway-system
  hostnames:
    - "www.example.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: backend
          port: 3000
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: ExtensionRef
          extensionRef:
            group: pixiu.apache.org
            kind: PixiuFilterPolicy
            name: jwt-filter-policy
