### dubbo proxy model

### one param, GetUserByName
POST http://localhost:8888/api/v1/test-dubbo/UserService/com.dubbogo.proxy.UserService?group=test&version=1.0.0&method=GetUserByName
Content-Type: application/json

{
  "types": [
    "string"
  ],
  "values": "tc"
}

### one param, GetUserByCode
POST http://localhost:8888/api/v1/test-dubbo/UserService/com.dubbogo.proxy.UserService?group=test&version=1.0.0&method=GetUserByCode
Content-Type: application/json

{
  "types": [
    "int"
  ],
  "values": 1
}

### multi params, UpdateUserByName
POST http://localhost:8888/api/v1/test-dubbo/UserService/com.dubbogo.proxy.UserService?group=test&version=1.0.0&method=UpdateUserByName
Content-Type: application/json

{
  "types": [
    "string",
    "body"
  ],
  "values": [
    "tc",
    {
      "id": "0001",
      "code": 1,
      "name": "tc",
      "age": 15
    }
  ]
}

### dubbo query model

### one param, GetUserByName
GET http://localhost:8888/api/v1/test-dubbo/userByName?name=tc
Content-Type: application/json

### multi params, GetUserByCode
GET http://localhost:8888/api/v1/test-dubbo/userByCode?code=1
Content-Type: application/json

### multi params, GetUserByNameAndAge
GET http://localhost:8888/api/v1/test-dubbo/userByNameAndAge?name=tc&age=99
Content-Type: application/json

### dubbo uri model

### one param, GetUserByName
GET http://localhost:8888/api/v1/test-dubbo/user/name/tc
Content-Type: application/json

### multi params, GetUserByCode
GET http://localhost:8888/api/v1/test-dubbo/user/code/1
Content-Type: application/json

### multi params, GetUserByNameAndAge
GET http://localhost:8888/api/v1/test-dubbo/user/name/tc/age/99
Content-Type: application/json

### dubbo body model

### add, CreateUser
POST http://localhost:8888/api/v1/test-dubbo/user
Content-Type: application/json

{
  "id": "0003",
  "code": 3,
  "name": "dubbogo",
  "age": 99
}

### add, UpdateUserByName
PUT http://localhost:8888/api/v1/test-dubbo/user2
Content-Type: application/json

{
  "name": "tc",
  "user": {
    "id": "0001",
    "code": 1,
    "name": "tc",
    "age": 99
  }
}

### modify, UpdateUser
PUT http://localhost:8888/api/v1/test-dubbo/user
Content-Type: application/json

{
  "id": "0003",
  "code": 3,
  "name": "dubbogo",
  "age": 18
}

### dubbo more than one model

### modify, GetUserByNameAndAge
GET http://localhost:8888/api/v1/test-dubbo/user/tc?age=99
Content-Type: application/json

### modify, UpdateUserByName
PUT http://localhost:8888/api/v1/test-dubbo/user/tc
Content-Type: application/json

{
  "id": "0001",
  "code": 1,
  "name": "tc",
  "age": 66
}

### modify, UpdateUserByName
PUT http://localhost:8888/api/v1/test-dubbo/user?name=tc
Content-Type: application/json

{
  "id": "0001",
  "code": 1,
  "name": "tc",
  "age": 55
}