# This rule is not used by the project controllers itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pixiu.apache.org.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllers
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-admin-role
rules:
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies
  verbs:
  - '*'
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies/status
  verbs:
  - get
