# This rule is not used by the project controllers itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to pixiu.apache.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllers
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-viewer-role
rules:
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies/status
  verbs:
  - get
