# This rule is not used by the project controllers itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the pixiu.apache.org.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: controllers
    app.kubernetes.io/managed-by: kustomize
  name: gatewayproxy-editor-role
rules:
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pixiu.apache.org
  resources:
  - gatewayproxies/status
  verbs:
  - get
