// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bootstrap.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HeaderValue
type HeaderValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeaderValue) Reset()         { *m = HeaderValue{} }
func (m *HeaderValue) String() string { return proto.CompactTextString(m) }
func (*HeaderValue) ProtoMessage()    {}
func (*HeaderValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{0}
}

func (m *HeaderValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeaderValue.Unmarshal(m, b)
}
func (m *HeaderValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeaderValue.Marshal(b, m, deterministic)
}
func (m *HeaderValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderValue.Merge(m, src)
}
func (m *HeaderValue) XXX_Size() int {
	return xxx_messageInfo_HeaderValue.Size(m)
}
func (m *HeaderValue) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderValue.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderValue proto.InternalMessageInfo

func (m *HeaderValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HeaderValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Tracing
type Http struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Http) Reset()         { *m = Http{} }
func (m *Http) String() string { return proto.CompactTextString(m) }
func (*Http) ProtoMessage()    {}
func (*Http) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{1}
}

func (m *Http) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Http.Unmarshal(m, b)
}
func (m *Http) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Http.Marshal(b, m, deterministic)
}
func (m *Http) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Http.Merge(m, src)
}
func (m *Http) XXX_Size() int {
	return xxx_messageInfo_Http.Size(m)
}
func (m *Http) XXX_DiscardUnknown() {
	xxx_messageInfo_Http.DiscardUnknown(m)
}

var xxx_messageInfo_Http proto.InternalMessageInfo

func (m *Http) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Metirc config for otel metric.
type Metric struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	PrometheusPort       int64    `protobuf:"varint,2,opt,name=prometheus_port,json=prometheusPort,proto3" json:"prometheus_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{2}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *Metric) GetPrometheusPort() int64 {
	if m != nil {
		return m.PrometheusPort
	}
	return 0
}

type PprofConf struct {
	Enable               bool     `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	Address              *Address `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PprofConf) Reset()         { *m = PprofConf{} }
func (m *PprofConf) String() string { return proto.CompactTextString(m) }
func (*PprofConf) ProtoMessage()    {}
func (*PprofConf) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{3}
}

func (m *PprofConf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PprofConf.Unmarshal(m, b)
}
func (m *PprofConf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PprofConf.Marshal(b, m, deterministic)
}
func (m *PprofConf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PprofConf.Merge(m, src)
}
func (m *PprofConf) XXX_Size() int {
	return xxx_messageInfo_PprofConf.Size(m)
}
func (m *PprofConf) XXX_DiscardUnknown() {
	xxx_messageInfo_PprofConf.DiscardUnknown(m)
}

var xxx_messageInfo_PprofConf proto.InternalMessageInfo

func (m *PprofConf) GetEnable() bool {
	if m != nil {
		return m.Enable
	}
	return false
}

func (m *PprofConf) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

// ShutdownConfig how to shutdown server.
type ShutdownConfig struct {
	Timeout              string   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	StepTimeout          string   `protobuf:"bytes,2,opt,name=step_timeout,json=stepTimeout,proto3" json:"step_timeout,omitempty"`
	RejectPolicy         string   `protobuf:"bytes,3,opt,name=reject_policy,json=rejectPolicy,proto3" json:"reject_policy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownConfig) Reset()         { *m = ShutdownConfig{} }
func (m *ShutdownConfig) String() string { return proto.CompactTextString(m) }
func (*ShutdownConfig) ProtoMessage()    {}
func (*ShutdownConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{4}
}

func (m *ShutdownConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownConfig.Unmarshal(m, b)
}
func (m *ShutdownConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownConfig.Marshal(b, m, deterministic)
}
func (m *ShutdownConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownConfig.Merge(m, src)
}
func (m *ShutdownConfig) XXX_Size() int {
	return xxx_messageInfo_ShutdownConfig.Size(m)
}
func (m *ShutdownConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownConfig proto.InternalMessageInfo

func (m *ShutdownConfig) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *ShutdownConfig) GetStepTimeout() string {
	if m != nil {
		return m.StepTimeout
	}
	return ""
}

func (m *ShutdownConfig) GetRejectPolicy() string {
	if m != nil {
		return m.RejectPolicy
	}
	return ""
}

// StaticResources
type StaticResources struct {
	Listeners            []*Listener     `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	Clusters             []*Cluster      `protobuf:"bytes,2,rep,name=clusters,proto3" json:"clusters,omitempty"`
	Adapters             []*Adapter      `protobuf:"bytes,3,rep,name=adapters,proto3" json:"adapters,omitempty"`
	ShutdownConfig       *ShutdownConfig `protobuf:"bytes,4,opt,name=shutdown_config,json=shutdownConfig,proto3" json:"shutdown_config,omitempty"`
	PprofConf            *PprofConf      `protobuf:"bytes,5,opt,name=pprof_conf,json=pprofConf,proto3" json:"pprof_conf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StaticResources) Reset()         { *m = StaticResources{} }
func (m *StaticResources) String() string { return proto.CompactTextString(m) }
func (*StaticResources) ProtoMessage()    {}
func (*StaticResources) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e3cc050d1b41a9e, []int{5}
}

func (m *StaticResources) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticResources.Unmarshal(m, b)
}
func (m *StaticResources) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticResources.Marshal(b, m, deterministic)
}
func (m *StaticResources) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticResources.Merge(m, src)
}
func (m *StaticResources) XXX_Size() int {
	return xxx_messageInfo_StaticResources.Size(m)
}
func (m *StaticResources) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticResources.DiscardUnknown(m)
}

var xxx_messageInfo_StaticResources proto.InternalMessageInfo

func (m *StaticResources) GetListeners() []*Listener {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *StaticResources) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

func (m *StaticResources) GetAdapters() []*Adapter {
	if m != nil {
		return m.Adapters
	}
	return nil
}

func (m *StaticResources) GetShutdownConfig() *ShutdownConfig {
	if m != nil {
		return m.ShutdownConfig
	}
	return nil
}

func (m *StaticResources) GetPprofConf() *PprofConf {
	if m != nil {
		return m.PprofConf
	}
	return nil
}

func init() {
	proto.RegisterType((*HeaderValue)(nil), "pixiu.api.v1.HeaderValue")
	proto.RegisterType((*Http)(nil), "pixiu.api.v1.Http")
	proto.RegisterType((*Metric)(nil), "pixiu.api.v1.Metric")
	proto.RegisterType((*PprofConf)(nil), "pixiu.api.v1.PprofConf")
	proto.RegisterType((*ShutdownConfig)(nil), "pixiu.api.v1.ShutdownConfig")
	proto.RegisterType((*StaticResources)(nil), "pixiu.api.v1.StaticResources")
}

func init() { proto.RegisterFile("bootstrap.proto", fileDescriptor_5e3cc050d1b41a9e) }

var fileDescriptor_5e3cc050d1b41a9e = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0x55, 0xba, 0xf9, 0x68, 0x26, 0x5f, 0xc8, 0x82, 0x62, 0x45, 0x1c, 0xca, 0x72, 0xa0, 0xa7,
	0x45, 0x2d, 0x1f, 0xf7, 0x52, 0x21, 0x15, 0x09, 0xa4, 0xc8, 0xad, 0x38, 0x70, 0x89, 0x9c, 0xdd,
	0x29, 0x35, 0x6c, 0xd6, 0x96, 0x3d, 0x5b, 0xe8, 0x7f, 0xe2, 0x47, 0xa2, 0xb5, 0xbd, 0x09, 0x2b,
	0xe8, 0x6d, 0xde, 0xbc, 0x37, 0x4f, 0x9e, 0x37, 0x86, 0xc5, 0x46, 0x6b, 0x72, 0x64, 0xa5, 0xc9,
	0x8c, 0xd5, 0xa4, 0xd9, 0xd4, 0xa8, 0x5f, 0xaa, 0xce, 0xa4, 0x51, 0xd9, 0xdd, 0xe9, 0x72, 0x26,
	0x8b, 0xc2, 0xa2, 0x73, 0x81, 0x5c, 0xce, 0xf2, 0xb2, 0x76, 0x84, 0xb6, 0x85, 0xb2, 0x90, 0x66,
	0x0f, 0xe7, 0xa5, 0x72, 0x84, 0x55, 0x8b, 0xd3, 0xb7, 0x30, 0xb9, 0x44, 0x59, 0xa0, 0xfd, 0x22,
	0xcb, 0x1a, 0xd9, 0x23, 0x48, 0x7e, 0xe0, 0x3d, 0xef, 0x1d, 0xf7, 0x4e, 0xc6, 0xa2, 0x29, 0xd9,
	0x63, 0x18, 0xdc, 0x35, 0x14, 0x3f, 0xf0, 0xbd, 0x00, 0xd2, 0x25, 0xf4, 0x2f, 0x89, 0x0c, 0x63,
	0xd0, 0xaf, 0xe4, 0x16, 0xe3, 0x80, 0xaf, 0xd3, 0x8f, 0x30, 0xfc, 0x8c, 0x64, 0x55, 0xce, 0x8e,
	0x60, 0x88, 0x95, 0xdc, 0x94, 0x81, 0x3f, 0x14, 0x11, 0xb1, 0x97, 0xb0, 0x30, 0x56, 0x6f, 0x91,
	0x6e, 0xb1, 0x76, 0x6b, 0xa3, 0x2d, 0x79, 0xf7, 0x44, 0xcc, 0xf7, 0xed, 0x95, 0xb6, 0x94, 0x5e,
	0xc3, 0x78, 0x65, 0xac, 0xbe, 0xb9, 0xd0, 0xd5, 0xcd, 0x83, 0x6e, 0xaf, 0x60, 0x14, 0x13, 0xf0,
	0x2e, 0x93, 0xb3, 0x27, 0xd9, 0xdf, 0xf9, 0x64, 0xe7, 0x81, 0x14, 0xad, 0x2a, 0xb5, 0x30, 0xbf,
	0xba, 0xad, 0xa9, 0xd0, 0x3f, 0xab, 0xc6, 0x58, 0x7d, 0x63, 0x1c, 0x46, 0xa4, 0xb6, 0xa8, 0x6b,
	0x8a, 0x9b, 0xb4, 0x90, 0x3d, 0x87, 0xa9, 0x23, 0x34, 0xeb, 0x96, 0x0e, 0x29, 0x4c, 0x9a, 0xde,
	0x75, 0x94, 0xbc, 0x80, 0x99, 0xc5, 0xef, 0x98, 0xd3, 0xda, 0xe8, 0x52, 0xe5, 0xf7, 0x3c, 0xf1,
	0x9a, 0x69, 0x68, 0xae, 0x7c, 0x2f, 0xfd, 0x7d, 0x00, 0x8b, 0x2b, 0x92, 0xa4, 0x72, 0x81, 0x4e,
	0xd7, 0x36, 0x47, 0xc7, 0xde, 0xc0, 0xb8, 0xbd, 0x86, 0xe3, 0xbd, 0xe3, 0xe4, 0x64, 0x72, 0x76,
	0xd4, 0x7d, 0xfa, 0xa7, 0x48, 0x8b, 0xbd, 0x90, 0x9d, 0xc2, 0x61, 0xbc, 0x70, 0xb3, 0x6f, 0xf2,
	0xef, 0xbe, 0x17, 0x81, 0x15, 0x3b, 0x59, 0x33, 0x12, 0x7f, 0x81, 0xe3, 0xc9, 0xff, 0x46, 0xce,
	0x03, 0x2b, 0x76, 0x32, 0xf6, 0x01, 0x16, 0x2e, 0x66, 0xb4, 0xce, 0x7d, 0x48, 0xbc, 0xef, 0xc3,
	0x7d, 0xd6, 0x9d, 0xec, 0x06, 0x29, 0xe6, 0xae, 0x1b, 0xec, 0x3b, 0x00, 0xd3, 0x1c, 0xd0, 0x7b,
	0xf0, 0x81, 0x77, 0x78, 0xda, 0x75, 0xd8, 0x1d, 0x58, 0x8c, 0x4d, 0x5b, 0xbe, 0x1f, 0x7d, 0x1d,
	0x6c, 0x75, 0x81, 0xe5, 0x66, 0xe8, 0xbf, 0xe9, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4a,
	0xbf, 0xb4, 0xb0, 0x04, 0x03, 0x00, 0x00,
}
