// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ApiConfigSource
type ApiConfigSource struct {
	ApitypeStr           string   `protobuf:"bytes,1,opt,name=apitype_str,json=apitypeStr,proto3" json:"apitype_str,omitempty"`
	ClusterName          []string `protobuf:"bytes,2,rep,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiConfigSource) Reset()         { *m = ApiConfigSource{} }
func (m *ApiConfigSource) String() string { return proto.CompactTextString(m) }
func (*ApiConfigSource) ProtoMessage()    {}
func (*ApiConfigSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *ApiConfigSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiConfigSource.Unmarshal(m, b)
}
func (m *ApiConfigSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiConfigSource.Marshal(b, m, deterministic)
}
func (m *ApiConfigSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiConfigSource.Merge(m, src)
}
func (m *ApiConfigSource) XXX_Size() int {
	return xxx_messageInfo_ApiConfigSource.Size(m)
}
func (m *ApiConfigSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiConfigSource.DiscardUnknown(m)
}

var xxx_messageInfo_ApiConfigSource proto.InternalMessageInfo

func (m *ApiConfigSource) GetApitypeStr() string {
	if m != nil {
		return m.ApitypeStr
	}
	return ""
}

func (m *ApiConfigSource) GetClusterName() []string {
	if m != nil {
		return m.ClusterName
	}
	return nil
}

// ConfigSource
type ConfigSource struct {
	Path                 string           `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ApiConfigSource      *ApiConfigSource `protobuf:"bytes,2,opt,name=api_config_source,json=apiConfigSource,proto3" json:"api_config_source,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ConfigSource) Reset()         { *m = ConfigSource{} }
func (m *ConfigSource) String() string { return proto.CompactTextString(m) }
func (*ConfigSource) ProtoMessage()    {}
func (*ConfigSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{1}
}

func (m *ConfigSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigSource.Unmarshal(m, b)
}
func (m *ConfigSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigSource.Marshal(b, m, deterministic)
}
func (m *ConfigSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigSource.Merge(m, src)
}
func (m *ConfigSource) XXX_Size() int {
	return xxx_messageInfo_ConfigSource.Size(m)
}
func (m *ConfigSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigSource.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigSource proto.InternalMessageInfo

func (m *ConfigSource) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ConfigSource) GetApiConfigSource() *ApiConfigSource {
	if m != nil {
		return m.ApiConfigSource
	}
	return nil
}

// EdsClusterConfig
type EdsClusterConfig struct {
	EdsConfig            *ConfigSource `protobuf:"bytes,1,opt,name=eds_config,json=edsConfig,proto3" json:"eds_config,omitempty"`
	ServiceName          string        `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *EdsClusterConfig) Reset()         { *m = EdsClusterConfig{} }
func (m *EdsClusterConfig) String() string { return proto.CompactTextString(m) }
func (*EdsClusterConfig) ProtoMessage()    {}
func (*EdsClusterConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{2}
}

func (m *EdsClusterConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdsClusterConfig.Unmarshal(m, b)
}
func (m *EdsClusterConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdsClusterConfig.Marshal(b, m, deterministic)
}
func (m *EdsClusterConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdsClusterConfig.Merge(m, src)
}
func (m *EdsClusterConfig) XXX_Size() int {
	return xxx_messageInfo_EdsClusterConfig.Size(m)
}
func (m *EdsClusterConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EdsClusterConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EdsClusterConfig proto.InternalMessageInfo

func (m *EdsClusterConfig) GetEdsConfig() *ConfigSource {
	if m != nil {
		return m.EdsConfig
	}
	return nil
}

func (m *EdsClusterConfig) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

// Cluster a single upstream cluster
type Cluster struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeStr              string            `protobuf:"bytes,2,opt,name=type_str,json=typeStr,proto3" json:"type_str,omitempty"`
	Type                 int32             `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	EdsClusterConfig     *EdsClusterConfig `protobuf:"bytes,4,opt,name=eds_cluster_config,json=edsClusterConfig,proto3" json:"eds_cluster_config,omitempty"`
	LbStr                string            `protobuf:"bytes,5,opt,name=lb_str,json=lbStr,proto3" json:"lb_str,omitempty"`
	Lb                   int32             `protobuf:"varint,6,opt,name=lb,proto3" json:"lb,omitempty"`
	HealthChecks         *HealthCheck      `protobuf:"bytes,7,opt,name=health_checks,json=healthChecks,proto3" json:"health_checks,omitempty"`
	Endpoints            *Endpoint         `protobuf:"bytes,8,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{3}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetTypeStr() string {
	if m != nil {
		return m.TypeStr
	}
	return ""
}

func (m *Cluster) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Cluster) GetEdsClusterConfig() *EdsClusterConfig {
	if m != nil {
		return m.EdsClusterConfig
	}
	return nil
}

func (m *Cluster) GetLbStr() string {
	if m != nil {
		return m.LbStr
	}
	return ""
}

func (m *Cluster) GetLb() int32 {
	if m != nil {
		return m.Lb
	}
	return 0
}

func (m *Cluster) GetHealthChecks() *HealthCheck {
	if m != nil {
		return m.HealthChecks
	}
	return nil
}

func (m *Cluster) GetEndpoints() *Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

// Endpoint
type Endpoint struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address              *SocketAddress    `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Endpoint) Reset()         { *m = Endpoint{} }
func (m *Endpoint) String() string { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()    {}
func (*Endpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{4}
}

func (m *Endpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Endpoint.Unmarshal(m, b)
}
func (m *Endpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Endpoint.Marshal(b, m, deterministic)
}
func (m *Endpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Endpoint.Merge(m, src)
}
func (m *Endpoint) XXX_Size() int {
	return xxx_messageInfo_Endpoint.Size(m)
}
func (m *Endpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Endpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Endpoint proto.InternalMessageInfo

func (m *Endpoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Endpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Endpoint) GetAddress() *SocketAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Endpoint) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// HealthCheck
type HealthCheck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheck) Reset()         { *m = HealthCheck{} }
func (m *HealthCheck) String() string { return proto.CompactTextString(m) }
func (*HealthCheck) ProtoMessage()    {}
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{5}
}

func (m *HealthCheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheck.Unmarshal(m, b)
}
func (m *HealthCheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheck.Marshal(b, m, deterministic)
}
func (m *HealthCheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheck.Merge(m, src)
}
func (m *HealthCheck) XXX_Size() int {
	return xxx_messageInfo_HealthCheck.Size(m)
}
func (m *HealthCheck) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheck.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ApiConfigSource)(nil), "pixiu.api.v1.ApiConfigSource")
	proto.RegisterType((*ConfigSource)(nil), "pixiu.api.v1.ConfigSource")
	proto.RegisterType((*EdsClusterConfig)(nil), "pixiu.api.v1.EdsClusterConfig")
	proto.RegisterType((*Cluster)(nil), "pixiu.api.v1.Cluster")
	proto.RegisterType((*Endpoint)(nil), "pixiu.api.v1.Endpoint")
	proto.RegisterMapType((map[string]string)(nil), "pixiu.api.v1.Endpoint.MetadataEntry")
	proto.RegisterType((*HealthCheck)(nil), "pixiu.api.v1.HealthCheck")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376) }

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x26, 0xe9, 0xff, 0x49, 0xe2, 0xd6, 0x41, 0x25, 0x5b, 0x51, 0xb3, 0xc1, 0x8b, 0x5c, 0x05,
	0xac, 0x0a, 0xfe, 0x80, 0xb8, 0x94, 0x05, 0x05, 0xf5, 0x62, 0x8a, 0xd7, 0x61, 0x92, 0x19, 0xcd,
	0xd0, 0x34, 0x19, 0x32, 0xd3, 0x62, 0x9f, 0xcc, 0x17, 0xf2, 0x41, 0x24, 0x93, 0x49, 0xdb, 0x94,
	0xbd, 0x3b, 0x73, 0xce, 0x77, 0xce, 0xf7, 0x43, 0x02, 0x5e, 0x56, 0xec, 0xa4, 0x62, 0x75, 0x2c,
	0xea, 0x4a, 0x55, 0xc8, 0x15, 0xfc, 0x0f, 0xdf, 0xc5, 0x44, 0xf0, 0x78, 0xff, 0x6a, 0xe1, 0x11,
	0x4a, 0x6b, 0x26, 0x65, 0x3b, 0x0c, 0x7f, 0xc2, 0xd5, 0xad, 0xe0, 0xab, 0xaa, 0xfc, 0xc5, 0x7f,
	0xaf, 0xab, 0x5d, 0x9d, 0x31, 0xf4, 0x02, 0x1c, 0x22, 0xb8, 0x3a, 0x08, 0x96, 0x48, 0x55, 0xfb,
	0x56, 0x60, 0x45, 0x33, 0x0c, 0xa6, 0xb5, 0x56, 0x35, 0xba, 0x01, 0xd7, 0x30, 0x24, 0x25, 0xd9,
	0x32, 0xdf, 0x0e, 0x06, 0xd1, 0x0c, 0x3b, 0xa6, 0xf7, 0x83, 0x6c, 0x59, 0xb8, 0x05, 0xb7, 0x77,
	0x13, 0xc1, 0x50, 0x10, 0x95, 0x9b, 0x63, 0xba, 0x46, 0x5f, 0xe1, 0x21, 0x11, 0x3c, 0xc9, 0x34,
	0x2e, 0x91, 0x1a, 0xe8, 0xdb, 0x81, 0x15, 0x39, 0xcb, 0x67, 0xf1, 0xb9, 0xe6, 0xf8, 0x42, 0x21,
	0xbe, 0x22, 0xfd, 0x46, 0x28, 0x60, 0x7e, 0x47, 0xe5, 0xaa, 0x15, 0xd0, 0x4e, 0xd0, 0x7b, 0x00,
	0x46, 0xa5, 0x39, 0xaf, 0x89, 0x9d, 0xe5, 0xa2, 0x7f, 0xb7, 0x77, 0x74, 0xc6, 0xa8, 0x34, 0xab,
	0x37, 0xe0, 0x4a, 0x56, 0xef, 0x79, 0xc6, 0x3a, 0x83, 0x8d, 0x6a, 0xc7, 0xf4, 0xb4, 0xc1, 0xbf,
	0x36, 0x4c, 0x0c, 0x5f, 0x63, 0x4e, 0xc3, 0x8c, 0xb9, 0xa6, 0x46, 0xd7, 0x30, 0x3d, 0x26, 0xd8,
	0xae, 0x4f, 0xba, 0xf8, 0x10, 0x0c, 0x9b, 0xd2, 0x1f, 0x04, 0x56, 0x34, 0xc2, 0xba, 0x46, 0xdf,
	0x00, 0x69, 0xb1, 0x26, 0x56, 0x23, 0x7a, 0xa8, 0x45, 0x3f, 0xef, 0x8b, 0xbe, 0x34, 0x8a, 0xe7,
	0xec, 0xd2, 0xfa, 0x63, 0x18, 0x17, 0xa9, 0xa6, 0x1e, 0x69, 0xea, 0x51, 0x91, 0x36, 0xc4, 0x0f,
	0xc0, 0x2e, 0x52, 0x7f, 0xac, 0x69, 0xed, 0x22, 0x45, 0x9f, 0xc0, 0xcb, 0x19, 0x29, 0x54, 0x9e,
	0x64, 0x39, 0xcb, 0x36, 0xd2, 0x9f, 0x68, 0xbe, 0xeb, 0x3e, 0xdf, 0x17, 0x0d, 0x59, 0x35, 0x08,
	0xec, 0xe6, 0xa7, 0x87, 0x44, 0x6f, 0x60, 0xc6, 0x4a, 0x2a, 0x2a, 0x5e, 0x2a, 0xe9, 0x4f, 0xf5,
	0xee, 0x93, 0x0b, 0xad, 0x66, 0x8c, 0x4f, 0xc0, 0xf0, 0x9f, 0x05, 0xd3, 0xae, 0xdf, 0x48, 0xe2,
	0xd4, 0x04, 0x67, 0x73, 0x7a, 0x8c, 0xd2, 0x3e, 0x8b, 0xf2, 0x2d, 0x4c, 0xcc, 0x37, 0xab, 0x23,
	0x73, 0x96, 0x4f, 0xfb, 0x24, 0xeb, 0x2a, 0xdb, 0x30, 0x75, 0xdb, 0x42, 0x70, 0x87, 0x45, 0x9f,
	0x61, 0xba, 0x65, 0x8a, 0x50, 0xa2, 0x88, 0x3f, 0x0c, 0x06, 0x91, 0xb3, 0x7c, 0x79, 0xbf, 0xb8,
	0xf8, 0xbb, 0x81, 0xdd, 0x95, 0xaa, 0x3e, 0xe0, 0xe3, 0xd6, 0xe2, 0x23, 0x78, 0xbd, 0x11, 0x9a,
	0xc3, 0x60, 0xc3, 0x0e, 0x46, 0x6e, 0x53, 0xa2, 0x47, 0x30, 0xda, 0x93, 0x62, 0xd7, 0x09, 0x6e,
	0x1f, 0x1f, 0xec, 0x77, 0x56, 0xe8, 0x81, 0x73, 0x96, 0x5c, 0x3a, 0xd6, 0xbf, 0xdb, 0xeb, 0xff,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x80, 0xdc, 0x95, 0x9c, 0x03, 0x00, 0x00,
}
