// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extension.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Message map to dubbo-go.pixiu//v1/discovery:cluster
type PixiuExtensionClusters struct {
	Clusters             []*Cluster `protobuf:"bytes,1,rep,name=clusters,proto3" json:"clusters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PixiuExtensionClusters) Reset()         { *m = PixiuExtensionClusters{} }
func (m *PixiuExtensionClusters) String() string { return proto.CompactTextString(m) }
func (*PixiuExtensionClusters) ProtoMessage()    {}
func (*PixiuExtensionClusters) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d065b70573ae483, []int{0}
}

func (m *PixiuExtensionClusters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixiuExtensionClusters.Unmarshal(m, b)
}
func (m *PixiuExtensionClusters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixiuExtensionClusters.Marshal(b, m, deterministic)
}
func (m *PixiuExtensionClusters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixiuExtensionClusters.Merge(m, src)
}
func (m *PixiuExtensionClusters) XXX_Size() int {
	return xxx_messageInfo_PixiuExtensionClusters.Size(m)
}
func (m *PixiuExtensionClusters) XXX_DiscardUnknown() {
	xxx_messageInfo_PixiuExtensionClusters.DiscardUnknown(m)
}

var xxx_messageInfo_PixiuExtensionClusters proto.InternalMessageInfo

func (m *PixiuExtensionClusters) GetClusters() []*Cluster {
	if m != nil {
		return m.Clusters
	}
	return nil
}

// Message map to dubbo-go.pixiu//v1/discovery:listener
type PixiuExtensionListeners struct {
	Listeners            []*Listener `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PixiuExtensionListeners) Reset()         { *m = PixiuExtensionListeners{} }
func (m *PixiuExtensionListeners) String() string { return proto.CompactTextString(m) }
func (*PixiuExtensionListeners) ProtoMessage()    {}
func (*PixiuExtensionListeners) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d065b70573ae483, []int{1}
}

func (m *PixiuExtensionListeners) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PixiuExtensionListeners.Unmarshal(m, b)
}
func (m *PixiuExtensionListeners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PixiuExtensionListeners.Marshal(b, m, deterministic)
}
func (m *PixiuExtensionListeners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PixiuExtensionListeners.Merge(m, src)
}
func (m *PixiuExtensionListeners) XXX_Size() int {
	return xxx_messageInfo_PixiuExtensionListeners.Size(m)
}
func (m *PixiuExtensionListeners) XXX_DiscardUnknown() {
	xxx_messageInfo_PixiuExtensionListeners.DiscardUnknown(m)
}

var xxx_messageInfo_PixiuExtensionListeners proto.InternalMessageInfo

func (m *PixiuExtensionListeners) GetListeners() []*Listener {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func init() {
	proto.RegisterType((*PixiuExtensionClusters)(nil), "pixiu.api.v1.PixiuExtensionClusters")
	proto.RegisterType((*PixiuExtensionListeners)(nil), "pixiu.api.v1.PixiuExtensionListeners")
}

func init() { proto.RegisterFile("extension.proto", fileDescriptor_2d065b70573ae483) }

var fileDescriptor_2d065b70573ae483 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xad, 0x28, 0x49,
	0xcd, 0x2b, 0xce, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0xc8, 0xac,
	0xc8, 0x2c, 0xd5, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x94, 0xe2, 0x4d, 0xce, 0x29, 0x2d, 0x2e,
	0x49, 0x2d, 0x82, 0x48, 0x4a, 0xf1, 0xe5, 0x64, 0x16, 0x97, 0xa4, 0xe6, 0xc1, 0xf8, 0x4a, 0xde,
	0x5c, 0x62, 0x01, 0x20, 0xe5, 0xae, 0x30, 0x43, 0x9c, 0x21, 0xca, 0x8b, 0x85, 0x0c, 0xb9, 0x38,
	0xa0, 0x5a, 0x8b, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x90, 0x4d, 0xd6, 0x83,
	0xaa, 0x0c, 0x82, 0x2b, 0x53, 0xf2, 0xe7, 0x12, 0x47, 0x35, 0xcc, 0x07, 0x6a, 0x59, 0xb1, 0x90,
	0x09, 0x17, 0x27, 0xcc, 0x66, 0x98, 0x71, 0x62, 0xa8, 0xc6, 0xc1, 0xd4, 0x06, 0x21, 0x14, 0x26,
	0xb1, 0x81, 0x1d, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x81, 0x02, 0x63, 0x1f, 0xe4, 0x00,
	0x00, 0x00,
}
