// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Filter core struct, filter is extend by user
type Filter struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Config:
	//	*Filter_Yaml
	//	*Filter_Json
	Config               isFilter_Config `protobuf_oneof:"config"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{0}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isFilter_Config interface {
	isFilter_Config()
}

type Filter_Yaml struct {
	Yaml *Config `protobuf:"bytes,2,opt,name=yaml,proto3,oneof"`
}

type Filter_Json struct {
	Json *Config `protobuf:"bytes,3,opt,name=json,proto3,oneof"`
}

func (*Filter_Yaml) isFilter_Config() {}

func (*Filter_Json) isFilter_Config() {}

func (m *Filter) GetConfig() isFilter_Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Filter) GetYaml() *Config {
	if x, ok := m.GetConfig().(*Filter_Yaml); ok {
		return x.Yaml
	}
	return nil
}

func (m *Filter) GetJson() *Config {
	if x, ok := m.GetConfig().(*Filter_Json); ok {
		return x.Json
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Filter) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Filter_Yaml)(nil),
		(*Filter_Json)(nil),
	}
}

type Config struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// FilterChain filter chain
type FilterChain struct {
	FilterChainMatch     *FilterChainMatch `protobuf:"bytes,1,opt,name=filter_chain_match,json=filterChainMatch,proto3" json:"filter_chain_match,omitempty"`
	Filters              []*Filter         `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FilterChain) Reset()         { *m = FilterChain{} }
func (m *FilterChain) String() string { return proto.CompactTextString(m) }
func (*FilterChain) ProtoMessage()    {}
func (*FilterChain) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{2}
}

func (m *FilterChain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterChain.Unmarshal(m, b)
}
func (m *FilterChain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterChain.Marshal(b, m, deterministic)
}
func (m *FilterChain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterChain.Merge(m, src)
}
func (m *FilterChain) XXX_Size() int {
	return xxx_messageInfo_FilterChain.Size(m)
}
func (m *FilterChain) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterChain.DiscardUnknown(m)
}

var xxx_messageInfo_FilterChain proto.InternalMessageInfo

func (m *FilterChain) GetFilterChainMatch() *FilterChainMatch {
	if m != nil {
		return m.FilterChainMatch
	}
	return nil
}

func (m *FilterChain) GetFilters() []*Filter {
	if m != nil {
		return m.Filters
	}
	return nil
}

// FilterChainMatch
type FilterChainMatch struct {
	Domains              []string `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterChainMatch) Reset()         { *m = FilterChainMatch{} }
func (m *FilterChainMatch) String() string { return proto.CompactTextString(m) }
func (*FilterChainMatch) ProtoMessage()    {}
func (*FilterChainMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{3}
}

func (m *FilterChainMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterChainMatch.Unmarshal(m, b)
}
func (m *FilterChainMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterChainMatch.Marshal(b, m, deterministic)
}
func (m *FilterChainMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterChainMatch.Merge(m, src)
}
func (m *FilterChainMatch) XXX_Size() int {
	return xxx_messageInfo_FilterChainMatch.Size(m)
}
func (m *FilterChainMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterChainMatch.DiscardUnknown(m)
}

var xxx_messageInfo_FilterChainMatch proto.InternalMessageInfo

func (m *FilterChainMatch) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

// HTTPFilter http filter
type HTTPFilter struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPFilter) Reset()         { *m = HTTPFilter{} }
func (m *HTTPFilter) String() string { return proto.CompactTextString(m) }
func (*HTTPFilter) ProtoMessage()    {}
func (*HTTPFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f5303cab7a20d6f, []int{4}
}

func (m *HTTPFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPFilter.Unmarshal(m, b)
}
func (m *HTTPFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPFilter.Marshal(b, m, deterministic)
}
func (m *HTTPFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPFilter.Merge(m, src)
}
func (m *HTTPFilter) XXX_Size() int {
	return xxx_messageInfo_HTTPFilter.Size(m)
}
func (m *HTTPFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPFilter.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPFilter proto.InternalMessageInfo

func (m *HTTPFilter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Filter)(nil), "pixiu.api.v1.Filter")
	proto.RegisterType((*Config)(nil), "pixiu.api.v1.Config")
	proto.RegisterType((*FilterChain)(nil), "pixiu.api.v1.FilterChain")
	proto.RegisterType((*FilterChainMatch)(nil), "pixiu.api.v1.FilterChainMatch")
	proto.RegisterType((*HTTPFilter)(nil), "pixiu.api.v1.HTTPFilter")
}

func init() { proto.RegisterFile("filter.proto", fileDescriptor_1f5303cab7a20d6f) }

var fileDescriptor_1f5303cab7a20d6f = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcb, 0xcc, 0x29,
	0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0xc8, 0xac, 0xc8, 0x2c, 0xd5,
	0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x54, 0xaa, 0xe3, 0x62, 0x73, 0x03, 0xcb, 0x0a, 0x09, 0x71,
	0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x5a,
	0x5c, 0x2c, 0x95, 0x89, 0xb9, 0x39, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0xc8,
	0x5a, 0xf5, 0x9c, 0xf3, 0xf3, 0xd2, 0x32, 0xd3, 0x3d, 0x18, 0x82, 0xc0, 0x6a, 0x40, 0x6a, 0xb3,
	0x8a, 0xf3, 0xf3, 0x24, 0x98, 0xf1, 0xab, 0x05, 0xa9, 0x71, 0xe2, 0xe0, 0x62, 0x4b, 0x06, 0x8b,
	0x28, 0x29, 0x71, 0xb1, 0x41, 0xe4, 0x84, 0x24, 0xb8, 0xd8, 0x93, 0xf3, 0xf3, 0x4a, 0x52, 0xf3,
	0x4a, 0xa0, 0x4e, 0x80, 0x71, 0x95, 0xba, 0x19, 0xb9, 0xb8, 0x21, 0x8e, 0x74, 0xce, 0x48, 0xcc,
	0xcc, 0x13, 0xf2, 0xe1, 0x12, 0x82, 0xf8, 0x28, 0x3e, 0x19, 0xc4, 0x8f, 0xcf, 0x4d, 0x2c, 0x49,
	0xce, 0x00, 0x6b, 0xe2, 0x36, 0x92, 0x43, 0xb5, 0x17, 0x49, 0x9b, 0x2f, 0x48, 0x55, 0x90, 0x40,
	0x1a, 0x9a, 0x88, 0x90, 0x1e, 0x17, 0x3b, 0x44, 0xac, 0x58, 0x82, 0x49, 0x81, 0x19, 0xd3, 0xe9,
	0x10, 0x23, 0x82, 0x60, 0x8a, 0x94, 0x74, 0xb8, 0x04, 0xd0, 0x4d, 0x05, 0xb9, 0x3d, 0x25, 0x3f,
	0x37, 0x31, 0x33, 0xaf, 0x58, 0x82, 0x51, 0x81, 0x19, 0xe4, 0x76, 0x28, 0x57, 0x49, 0x81, 0x8b,
	0xcb, 0x23, 0x24, 0x24, 0x00, 0x77, 0x18, 0x27, 0xb1, 0x81, 0xa3, 0xc5, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x84, 0xab, 0x50, 0xa6, 0x01, 0x00, 0x00,
}
