// Code generated by protoc-gen-go. DO NOT EDIT.
// source: listener.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Listener is a server, listener a port
type Listener struct {
	Name                 string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address       `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FilterChains         []*FilterChain `protobuf:"bytes,3,rep,name=filter_chains,json=filterChains,proto3" json:"filter_chains,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Listener) Reset()         { *m = Listener{} }
func (m *Listener) String() string { return proto.CompactTextString(m) }
func (*Listener) ProtoMessage()    {}
func (*Listener) Descriptor() ([]byte, []int) {
	return fileDescriptor_f75aade3a9f7de9c, []int{0}
}

func (m *Listener) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listener.Unmarshal(m, b)
}
func (m *Listener) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listener.Marshal(b, m, deterministic)
}
func (m *Listener) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listener.Merge(m, src)
}
func (m *Listener) XXX_Size() int {
	return xxx_messageInfo_Listener.Size(m)
}
func (m *Listener) XXX_DiscardUnknown() {
	xxx_messageInfo_Listener.DiscardUnknown(m)
}

var xxx_messageInfo_Listener proto.InternalMessageInfo

func (m *Listener) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Listener) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Listener) GetFilterChains() []*FilterChain {
	if m != nil {
		return m.FilterChains
	}
	return nil
}

func init() {
	proto.RegisterType((*Listener)(nil), "pixiu.api.v1.Listener")
}

func init() { proto.RegisterFile("listener.proto", fileDescriptor_f75aade3a9f7de9c) }

var fileDescriptor_f75aade3a9f7de9c = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xc9, 0x2c, 0x2e,
	0x49, 0xcd, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x29, 0xc8, 0xac, 0xc8,
	0x2c, 0xd5, 0x4b, 0x2c, 0xc8, 0xd4, 0x2b, 0x33, 0x94, 0xe2, 0x4d, 0x4c, 0x49, 0x29, 0x4a, 0x2d,
	0x2e, 0x86, 0x48, 0x4a, 0xf1, 0xa4, 0x65, 0xe6, 0x94, 0xc0, 0x94, 0x2a, 0xf5, 0x33, 0x72, 0x71,
	0xf8, 0x40, 0x75, 0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x81, 0xd9, 0x42, 0xfa, 0x5c, 0xec, 0x50, 0xfd, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0xa2, 0x7a, 0xc8, 0xa6, 0xeb, 0x39, 0x42, 0x24, 0x83, 0x60, 0xaa, 0x84, 0xec, 0xb8, 0x78,
	0x21, 0x36, 0xc4, 0x27, 0x67, 0x24, 0x66, 0xe6, 0x15, 0x4b, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b,
	0x49, 0xa2, 0x6a, 0x73, 0x03, 0x2b, 0x71, 0x06, 0xa9, 0x08, 0x82, 0xba, 0x08, 0xcc, 0x29, 0x4e,
	0x62, 0x03, 0x3b, 0xcc, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x06, 0xf3, 0x0d, 0x4d, 0xd5, 0x00,
	0x00, 0x00,
}
