// Code generated by protoc-gen-go. DO NOT EDIT.
// source: route.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// RouteAction match route should do
type RouteAction struct {
	Cluster                     string   `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	ClusterNotFoundResponseCode int64    `protobuf:"varint,2,opt,name=cluster_not_found_response_code,json=clusterNotFoundResponseCode,proto3" json:"cluster_not_found_response_code,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *RouteAction) Reset()         { *m = RouteAction{} }
func (m *RouteAction) String() string { return proto.CompactTextString(m) }
func (*RouteAction) ProtoMessage()    {}
func (*RouteAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{0}
}

func (m *RouteAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteAction.Unmarshal(m, b)
}
func (m *RouteAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteAction.Marshal(b, m, deterministic)
}
func (m *RouteAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteAction.Merge(m, src)
}
func (m *RouteAction) XXX_Size() int {
	return xxx_messageInfo_RouteAction.Size(m)
}
func (m *RouteAction) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteAction.DiscardUnknown(m)
}

var xxx_messageInfo_RouteAction proto.InternalMessageInfo

func (m *RouteAction) GetCluster() string {
	if m != nil {
		return m.Cluster
	}
	return ""
}

func (m *RouteAction) GetClusterNotFoundResponseCode() int64 {
	if m != nil {
		return m.ClusterNotFoundResponseCode
	}
	return 0
}

// RouteConfiguration
type RouteConfiguration struct {
	Routes               []*Router `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	Dynamic              bool      `protobuf:"varint,2,opt,name=dynamic,proto3" json:"dynamic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RouteConfiguration) Reset()         { *m = RouteConfiguration{} }
func (m *RouteConfiguration) String() string { return proto.CompactTextString(m) }
func (*RouteConfiguration) ProtoMessage()    {}
func (*RouteConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{1}
}

func (m *RouteConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteConfiguration.Unmarshal(m, b)
}
func (m *RouteConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteConfiguration.Marshal(b, m, deterministic)
}
func (m *RouteConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteConfiguration.Merge(m, src)
}
func (m *RouteConfiguration) XXX_Size() int {
	return xxx_messageInfo_RouteConfiguration.Size(m)
}
func (m *RouteConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_RouteConfiguration proto.InternalMessageInfo

func (m *RouteConfiguration) GetRoutes() []*Router {
	if m != nil {
		return m.Routes
	}
	return nil
}

func (m *RouteConfiguration) GetDynamic() bool {
	if m != nil {
		return m.Dynamic
	}
	return false
}

type Router struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Match                *RouterMatch `protobuf:"bytes,2,opt,name=match,proto3" json:"match,omitempty"`
	Route                *RouteAction `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Router) Reset()         { *m = Router{} }
func (m *Router) String() string { return proto.CompactTextString(m) }
func (*Router) ProtoMessage()    {}
func (*Router) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{2}
}

func (m *Router) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Router.Unmarshal(m, b)
}
func (m *Router) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Router.Marshal(b, m, deterministic)
}
func (m *Router) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Router.Merge(m, src)
}
func (m *Router) XXX_Size() int {
	return xxx_messageInfo_Router.Size(m)
}
func (m *Router) XXX_DiscardUnknown() {
	xxx_messageInfo_Router.DiscardUnknown(m)
}

var xxx_messageInfo_Router proto.InternalMessageInfo

func (m *Router) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Router) GetMatch() *RouterMatch {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *Router) GetRoute() *RouteAction {
	if m != nil {
		return m.Route
	}
	return nil
}

// RouterMatch
type RouterMatch struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Methods              []string `protobuf:"bytes,3,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouterMatch) Reset()         { *m = RouterMatch{} }
func (m *RouterMatch) String() string { return proto.CompactTextString(m) }
func (*RouterMatch) ProtoMessage()    {}
func (*RouterMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_0984d49a362b6b9f, []int{3}
}

func (m *RouterMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouterMatch.Unmarshal(m, b)
}
func (m *RouterMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouterMatch.Marshal(b, m, deterministic)
}
func (m *RouterMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouterMatch.Merge(m, src)
}
func (m *RouterMatch) XXX_Size() int {
	return xxx_messageInfo_RouterMatch.Size(m)
}
func (m *RouterMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RouterMatch.DiscardUnknown(m)
}

var xxx_messageInfo_RouterMatch proto.InternalMessageInfo

func (m *RouterMatch) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *RouterMatch) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RouterMatch) GetMethods() []string {
	if m != nil {
		return m.Methods
	}
	return nil
}

func init() {
	proto.RegisterType((*RouteAction)(nil), "pixiu.api.v1.RouteAction")
	proto.RegisterType((*RouteConfiguration)(nil), "pixiu.api.v1.RouteConfiguration")
	proto.RegisterType((*Router)(nil), "pixiu.api.v1.Router")
	proto.RegisterType((*RouterMatch)(nil), "pixiu.api.v1.RouterMatch")
}

func init() { proto.RegisterFile("route.proto", fileDescriptor_0984d49a362b6b9f) }

var fileDescriptor_0984d49a362b6b9f = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xab, 0xd5, 0x9d, 0x8a, 0x87, 0x20, 0x12, 0xf1, 0x60, 0xe9, 0xa9, 0x07, 0xa9,
	0xb8, 0x7e, 0x02, 0x59, 0xf1, 0xa6, 0x87, 0x78, 0x15, 0x4a, 0x6d, 0x52, 0x37, 0x60, 0x33, 0x21,
	0x4d, 0x64, 0xf5, 0xd3, 0x4b, 0xfe, 0x2c, 0x78, 0xd0, 0xdb, 0x3c, 0xfa, 0x7b, 0x7d, 0x6f, 0x26,
	0x50, 0x19, 0x74, 0x56, 0x74, 0xda, 0xa0, 0x45, 0x72, 0xa2, 0xe5, 0x4e, 0xba, 0x6e, 0xd0, 0xb2,
	0xfb, 0xbc, 0x6d, 0x66, 0xa8, 0x98, 0xff, 0x78, 0x3f, 0x5a, 0x89, 0x8a, 0x50, 0x38, 0x1a, 0x3f,
	0xdc, 0x62, 0x85, 0xa1, 0x59, 0x9d, 0xb5, 0x2b, 0xb6, 0x97, 0xe4, 0x01, 0xae, 0xd2, 0xd8, 0x2b,
	0xb4, 0xfd, 0x84, 0x4e, 0xf1, 0xde, 0x88, 0x45, 0xa3, 0x5a, 0x44, 0x3f, 0x22, 0x17, 0x34, 0xaf,
	0xb3, 0xb6, 0x60, 0x97, 0x09, 0x7b, 0x46, 0xfb, 0xe8, 0x21, 0x96, 0x98, 0x0d, 0x72, 0xd1, 0xbc,
	0x02, 0x09, 0x71, 0x1b, 0x54, 0x93, 0x7c, 0x77, 0x66, 0x08, 0xa9, 0xd7, 0x50, 0x86, 0x86, 0x0b,
	0xcd, 0xea, 0xa2, 0xad, 0xd6, 0x67, 0xdd, 0xef, 0x8e, 0x5d, 0x70, 0x18, 0x96, 0x18, 0xdf, 0x91,
	0x7f, 0xa9, 0x61, 0x96, 0x63, 0x48, 0x3c, 0x66, 0x7b, 0xd9, 0x7c, 0x43, 0x19, 0x59, 0x72, 0x0a,
	0xb9, 0xe4, 0x69, 0x85, 0x5c, 0x72, 0x72, 0x03, 0x87, 0xf3, 0x60, 0xc7, 0x6d, 0x70, 0x54, 0xeb,
	0x8b, 0xbf, 0x02, 0x9e, 0x3c, 0xc0, 0x22, 0xe7, 0x0d, 0x21, 0x8e, 0x16, 0xff, 0x1a, 0xe2, 0xc9,
	0x58, 0xe4, 0x9a, 0x97, 0x74, 0xc8, 0xf8, 0x1b, 0x72, 0x0e, 0xa5, 0x36, 0x62, 0x92, 0xbb, 0x54,
	0x22, 0x29, 0x42, 0xe0, 0x40, 0x0f, 0x36, 0xf6, 0x58, 0xb1, 0x30, 0xfb, 0x85, 0x66, 0x61, 0xb7,
	0xc8, 0x17, 0x5a, 0xd4, 0x85, 0x3f, 0x7a, 0x92, 0x6f, 0x65, 0x78, 0xb2, 0xbb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3f, 0x65, 0x2c, 0x37, 0xc1, 0x01, 0x00, 0x00,
}
