- name: "/api/v1/test-dubbo/user"
  itype: "HTTP"
  otype: "DUBBO"
  method: "POST"
  status: 1
  metadata:
    - dubbo:
        - application_name: "BDTService"
        - group: "test"
        - version: "1.0.0"
        - interface: "com.ikurento.user.UserProvider"
        - method: "queryUser"
        - cluster_name: "test_dubbo"
        - types:
            - "com.ikurento.user.User"
