---
apiVersion: v1
kind: Namespace
metadata:
  name: pixiu-gateway-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: pg-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pg-controller
  namespace: pixiu-gateway-system
  labels:
    app.kubernetes.io/name: pg-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pg-controller-role
  labels:
    app.kubernetes.io/name: pg-controller
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  - referencegrants/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - referencegrants
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - secrets
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pg-controller-rolebinding
  labels:
    app.kubernetes.io/name: pg-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pg-controller-role
subjects:
- kind: ServiceAccount
  name: pg-controller
  namespace: pixiu-gateway-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-controller
  namespace: pixiu-gateway-system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: pg-controller
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: pg-controller
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app.kubernetes.io/name: pg-controller
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
            - /usr/local/bin/pg-controller
        args:
        - --config-path=/config/pg.yaml
        - --log-level=info
        image: mfordjody/pixiugateway-controller:debug
        imagePullPolicy: Always
        name: manager
        ports:
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 64Mi
      volumes:
      - name: config
        configMap:
          name: pg
      serviceAccountName: pg-controller
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pg-controller
  namespace: pixiu-gateway-system
spec:
  selector:
    app.kubernetes.io/name: pg-controller
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg
  namespace: pixiu-gateway-system
data:
  pg.yaml: |
    log_level: info
    controller_name: pixiu.apache.org/pixiu-gateway-controller
