name: proxy
description: proxy sample
resources:
  - path: '/api/v1/test-http/user'
    type: restful
    description: user
    methods:
      - httpVerb: GET
        onAir: true
        timeout: 1000ms
        inboundRequest:
          requestType: http
          queryStrings:
            - name: name
              required: true
        integrationRequest:
          requestType: http
          mappingParams:
            - name: queryStrings.username
              mapTo: queryStrings.name
          host: "127.0.0.1:1314"
          path: "/user"
      - httpVerb: POST
        onAir: true
        timeout: 10s
        inboundRequest:
          requestType: http
        integrationRequest:
          requestType: http
          host: "127.0.0.1:1314"
          path: "/user/"
    resources:
      - path: '/:name'
        type: restful
        description: user2
        methods:
          - httpVerb: GET
            onAir: true
            timeout: 1000ms
            inboundRequest:
              requestType: http
              queryStrings:
                - name: name
                  required: true
            integrationRequest:
              requestType: http
              mappingParams:
                - name: uri.name
                  mapTo: uri.name
              host: "127.0.0.1:1314"
              path: "/user/:name"
definitions:
  - name: userCreate
    schema: >-
      {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "age" : {
            "type" : "integer"
          }
        }
      }
