//go:build !wireinject
// +build !wireinject

/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire

package wire

import (
	"github.com/apache/dubbo-go-pixiu/admin/internal/handler"
	"github.com/apache/dubbo-go-pixiu/admin/internal/store"
)

// Injectors from wire.go:

// InitializeApp creates all application dependencies using wire.
func InitializeApp(configPath ConfigPath) (*App, func(), error) {
	config, err := ProvideConfig(configPath)
	if err != nil {
		return nil, nil, err
	}
	logger, err := ProvideLogger(config)
	if err != nil {
		return nil, nil, err
	}
	mySQLConfig := ProvideMySQLConfig(config)
	mySQL, err := store.NewMySQL(mySQLConfig)
	if err != nil {
		return nil, nil, err
	}
	etcdConfig := ProvideEtcdConfig(config)
	jwtConfig := ProvideJWTConfig(config)
	client, cleanup, err := ProvideEtcdClient(etcdConfig)
	if err != nil {
		return nil, nil, err
	}
	etcdBasePath := ProvideEtcdBasePath(etcdConfig)
	etcd := ProvideEtcdStore(client, etcdBasePath)
	handlerHandler := handler.New(mySQL, etcd, logger, jwtConfig)
	xdsPort := ProvideXDSPort()
	server := ProvideXDSServer(etcd, logger, xdsPort)
	app := NewApp(config, logger, mySQL, etcd, handlerHandler, server)
	return app, func() {
		cleanup()
	}, nil
}
