resources:
  - name: test-dubbo
    items:
      #Accurate
      - matchStrategy: 0
        pattern: "/api/v1/test-dubbo/user"
      #Regex
      - matchStrategy: 1
        pattern: "/api/v1/test-dubbo/user/*"
  - name: test-http
    items:
      #Accurate
      - matchStrategy: 0
        pattern: "/api/v1/http/foo"
      - matchStrategy: 0
        pattern: "/api/v1/http/bar"
      #Regex
      - matchStrategy: 1
        pattern: "/api/v1/http/foo/*"
      - matchStrategy: 1
        pattern: "/api/v1/http/bar/*"

rules:
  #qps sample At most 100 requests can be passed in 1000ms, so qps is 100
  - resource: "test-dubbo"
    enable: true
    threshold: 100
    statintervalinms: 1000