// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: listener.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listener_Protocols int32

const (
	Listener_HTTP   Listener_Protocols = 0
	Listener_TCP    Listener_Protocols = 1
	Listener_UDP    Listener_Protocols = 2
	Listener_HTTPS  Listener_Protocols = 3
	Listener_GRPC   Listener_Protocols = 4
	Listener_HTTP2  Listener_Protocols = 5
	Listener_TRIPLE Listener_Protocols = 6
)

// Enum value maps for Listener_Protocols.
var (
	Listener_Protocols_name = map[int32]string{
		0: "HTTP",
		1: "TCP",
		2: "UDP",
		3: "HTTPS",
		4: "GRPC",
		5: "HTTP2",
		6: "TRIPLE",
	}
	Listener_Protocols_value = map[string]int32{
		"HTTP":   0,
		"TCP":    1,
		"UDP":    2,
		"HTTPS":  3,
		"GRPC":   4,
		"HTTP2":  5,
		"TRIPLE": 6,
	}
)

func (x Listener_Protocols) Enum() *Listener_Protocols {
	p := new(Listener_Protocols)
	*p = x
	return p
}

func (x Listener_Protocols) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listener_Protocols) Descriptor() protoreflect.EnumDescriptor {
	return file_listener_proto_enumTypes[0].Descriptor()
}

func (Listener_Protocols) Type() protoreflect.EnumType {
	return &file_listener_proto_enumTypes[0]
}

func (x Listener_Protocols) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listener_Protocols.Descriptor instead.
func (Listener_Protocols) EnumDescriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0, 0}
}

// Listener is a server, listener a port
type Listener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address     *Address           `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	FilterChain *FilterChain       `protobuf:"bytes,3,opt,name=filter_chain,json=filterChain,proto3" json:"filter_chain,omitempty"`
	Protocol    Listener_Protocols `protobuf:"varint,4,opt,name=protocol,proto3,enum=pixiu.api.v1.Listener_Protocols" json:"protocol,omitempty"`
}

func (x *Listener) Reset() {
	*x = Listener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Listener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listener) ProtoMessage() {}

func (x *Listener) ProtoReflect() protoreflect.Message {
	mi := &file_listener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listener.ProtoReflect.Descriptor instead.
func (*Listener) Descriptor() ([]byte, []int) {
	return file_listener_proto_rawDescGZIP(), []int{0}
}

func (x *Listener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listener) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Listener) GetFilterChain() *FilterChain {
	if x != nil {
		return x.FilterChain
	}
	return nil
}

func (x *Listener) GetProtocol() Listener_Protocols {
	if x != nil {
		return x.Protocol
	}
	return Listener_HTTP
}

var File_listener_proto protoreflect.FileDescriptor

var file_listener_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x0d,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x02, 0x0a, 0x08,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3c, 0x0a,
	0x0c, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x0b,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x3c, 0x0a, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e,
	0x70, 0x69, 0x78, 0x69, 0x75, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x52,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x53, 0x0a, 0x09, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x54, 0x50, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x43, 0x50, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x55, 0x44, 0x50,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x53, 0x10, 0x03, 0x12, 0x08, 0x0a,
	0x04, 0x47, 0x52, 0x50, 0x43, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x48, 0x54, 0x54, 0x50, 0x32,
	0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x52, 0x49, 0x50, 0x4c, 0x45, 0x10, 0x06, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_listener_proto_rawDescOnce sync.Once
	file_listener_proto_rawDescData = file_listener_proto_rawDesc
)

func file_listener_proto_rawDescGZIP() []byte {
	file_listener_proto_rawDescOnce.Do(func() {
		file_listener_proto_rawDescData = protoimpl.X.CompressGZIP(file_listener_proto_rawDescData)
	})
	return file_listener_proto_rawDescData
}

var file_listener_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_listener_proto_goTypes = []interface{}{
	(Listener_Protocols)(0), // 0: pixiu.api.v1.Listener.Protocols
	(*Listener)(nil),        // 1: pixiu.api.v1.Listener
	(*Address)(nil),         // 2: pixiu.api.v1.Address
	(*FilterChain)(nil),     // 3: pixiu.api.v1.FilterChain
}
var file_listener_proto_depIdxs = []int32{
	2, // 0: pixiu.api.v1.Listener.address:type_name -> pixiu.api.v1.Address
	3, // 1: pixiu.api.v1.Listener.filter_chain:type_name -> pixiu.api.v1.FilterChain
	0, // 2: pixiu.api.v1.Listener.protocol:type_name -> pixiu.api.v1.Listener.Protocols
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_listener_proto_init() }
func file_listener_proto_init() {
	if File_listener_proto != nil {
		return
	}
	file_address_proto_init()
	file_filter_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_listener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Listener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listener_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listener_proto_goTypes,
		DependencyIndexes: file_listener_proto_depIdxs,
		EnumInfos:         file_listener_proto_enumTypes,
		MessageInfos:      file_listener_proto_msgTypes,
	}.Build()
	File_listener_proto = out.File
	file_listener_proto_rawDesc = nil
	file_listener_proto_goTypes = nil
	file_listener_proto_depIdxs = nil
}
