# - name: "test-dubbo/user"
#   target: "queryUser"
#   method: "POST"
#   types:
#     - "com.ikurento.user.User"

name: api name
description: api description
resources:
  - path: '/'
    description: resource documentation
    filters:
      - filterA
      - filterB
    methods:
      - method: GET
        inboundRequest:
          type: http
          headers: 
            - name: auth
            - required: true 
          queryStrings:
            - name: page
              required: false
            - name: type
              required: false
          requestBody:
            - modelDefinition
        integrationRequest:
          type: dubbo
          paramTypes:
            - "com.ikurento.user.User"


Definitions:
  - name: modelDefinition
    contentType: application/json
    schema: >-
      {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "type" : {
            "type" : "string"
          },
          "price" : {
            "type" : "number"
          }
        }
      }
