# We set up anonymous authentication as this is for demos.
auth:
  strategy: anonymous
deployment:
  pod_labels:
    sidecar.istio.io/inject: "false"
  accessible_namespaces:
  - '**'
  ingress_enabled: false
  hpa:
    api_version: autoscaling/v2beta2
login_token:
  signing_key: CHANGEME00000000
