name: proxy
description: proxy sample
resources:
  - path: '/api/v1/test-dubbo/user'
    type: restful
    description: user
    filters:
      - filter0
    methods:
      - httpVerb: GET
        onAir: true
        timeout: 100ms
        inboundRequest:
          requestType: http
          queryStrings:
            - name: name
              type: string
              required: true
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: queryStrings.name
              mapTo: 0
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "GetUserByName"
          paramTypes: [ "java.lang.String" ]
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
      - httpVerb: POST
        onAir: true
        timeout: 10s
        inboundRequest:
          requestType: http
#          requestBody:
#            - definitionName: "userCreate"
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: requestBody._all
              mapTo: 0
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "CreateUser"
          paramTypes: [ "com.ikurento.user.User" ]
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
  - path: '/api/v1/test-dubbo/timeout-user'
    type: restful
    description: user
    filters:
      - filter0
    methods:
      - httpVerb: GET
        onAir: true
        timeout: 1s
        inboundRequest:
          requestType: http
          queryStrings:
            - name: name
              type: string
              required: true
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: queryStrings.name
              mapTo: 1
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "GetUserTimeout"
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
  - path: '/api/v1/test-dubbo/user-add'
    type: restful
    description: user
    methods:
      - httpVerb: POST
        onAir: true
        timeout: 10s
        inboundRequest:
          requestType: http
        integrationRequest:
          requestType: dubbo
          mappingParams:
            - name: requestBody.name
              mapTo: 0
            - name: requestBody.id
              mapTo: 1
            - name: requestBody.age
              mapTo: 2
          applicationName: "UserProvider"
          interface: "com.ic.user.UserProvider"
          method: "CreateUser"
          paramTypes: [ "com.ikurento.user.User" ]
          group: "test"
          version: 1.0.0
          clusterName: "test_dubbo"
definitions:
  - name: userCreate
    schema: >-
      {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer"
          },
          "name" : {
            "type" : "string"
          },
          "age" : {
            "type" : "integer"
          }
        }
      }
